export const AGENT_INSTRUCTIONS = `# Visual Source

This directory holds the design tokens for the project — color palettes, color tokens, spacing tokens, themes — plus the CSS and JSON files generated from them.

## Files

- \`manifest.json\` — source of truth. Hand-editable.
- \`visual-source.css\` — generated CSS custom properties. Do not edit; regenerated from \`manifest.json\`.
- \`visual-source.json\` — generated resolved token values. Do not edit; regenerated from \`manifest.json\`.
- \`AGENTS.md\` / \`CLAUDE.md\` — these instructions. Regenerated by the GUI on save.

## Editing workflow

1. Edit \`manifest.json\` directly.
2. Run \`visual-source validate\` to check schema and reference integrity. On success it prints nothing and exits 0.
3. Run \`visual-source regenerate\` to rewrite \`visual-source.css\` and \`visual-source.json\`.

\`regenerate\` runs \`validate\` first and refuses to write outputs if validation fails. Pass \`--skip-validate\` to bypass.

### Allocating IDs

Every entity (palette, token, group, theme) needs a numeric \`id\` that's unique within its collection. When adding a new entity, pick \`max(existing ids) + 1\`. IDs do not need to be contiguous; deleted entities leave gaps and that's fine.

## Other CLI commands

- \`visual-source show\` — pretty-print \`manifest.json\` to stdout.
- \`visual-source path\` — print the absolute path of \`manifest.json\`.

## Post-generation hook

If a \`generate\` executable exists in this directory, it is invoked (with this
directory as the working directory) immediately after \`visual-source.css\` and
\`visual-source.json\` are written — both by the GUI's auto-save and by
\`visual-source regenerate\`. Use it to run any downstream step that should track
token changes (e.g. copy outputs into another package, run a build, commit the
result). It must be executable (\`chmod +x generate\`). A non-zero exit fails
\`visual-source regenerate\`; in the GUI the error is logged to the console and
auto-save continues.

## Recommended structure

The intended way to organize tokens with this tool is **contextual grouping with context classes**. Follow this unless you have a clear reason not to.

1. Define one group per UI surface or semantic context: \`Background\`, \`Surface\`, \`Primary\`, \`Field\`, \`Error\`, etc.
2. Inside each group, define the same set of role tokens — \`Text 01\`, \`Text 02\`, \`Border\`, \`Hover\`, \`Disabled\`, … — as needed for that context. Use **consistent names across groups** (every group's text token is called \`Text 01\`, not \`text\` in one and \`label\` in another).
3. Give each group a \`css.prefix\` matching its name (e.g. \`bg-\`, \`surface-\`, \`primary-\`).
4. Set \`context: true\` on every group that represents a surface a component might be rendered inside. Order matters: put the page-wide default group (usually \`Background\`) **first**, since the first context group also applies to \`:root\`.

With this setup, components write context-agnostic CSS:

\`\`\`css
.card {
  background: var(--bg);
  color: var(--text-01);
  border: 1px solid var(--border);
}
.card .help { color: var(--text-02); }
.card:hover { background: var(--hover); }
\`\`\`

…and the surrounding wrapper picks the context:

\`\`\`html
<div class="surface"> … card renders against surface tokens … </div>
<div class="error">   … same card renders against error tokens   … </div>
\`\`\`

Consumers should reach for the unprefixed form (\`--text-01\`) by default and only use the fully prefixed form (\`--bg-text-01\`, \`--error-text-01\`) when they explicitly need a token from a context they aren't inside — for example, an error message rendered on a neutral surface.

### When to deviate

- **Non-contextual tokens** — focus rings, scrim/overlay, brand-fixed accents, anchor link colors, selection highlight, and similar values that should look the same regardless of which surface they're rendered on belong in groups with \`context: false\` (or omitted). They're emitted as plain CSS variables only.
- **Cross-cutting tokens** — values that don't logically belong to a single surface (e.g. shadow elevations, radii) likewise stay non-contextual.
- If you find yourself wanting "the text color but slightly muted in this one place," prefer adding a \`Text 03\` to every context group over reaching across contexts. The matrix grows linearly, and consistency matters more than token count.

## Schema

\`manifest.json\` has the shape:

\`\`\`
{
  "version": 2,
  "color": {
    "palettes": Palette[],
    "tokens":   Token[],
    "groups":   TokenGroup[]
  },
  "spacing": { "scale": Token[] },
  "general": {
    "tokens": Token[],
    "groups": TokenGroup[]
  },
  "themes":  Theme[]
}
\`\`\`

- **Palette** — \`{ id, name, colors: string[] }\`. \`colors\` is an array of hex strings.
- **Token** — \`{ id, name, value? | $ref?, css?: { name? } }\`. Exactly one of \`value\` (a hex or CSS-length string) or \`$ref\` must be present.
- **TokenGroup** — \`{ id, name, tokens: number[], context?: boolean, css?: { prefix? } }\`. \`tokens\` is a list of token \`id\`s; \`css.prefix\` is prepended to each token's CSS variable name. When \`context\` is \`true\`, the group also generates a context class — see *Context groups* below. **Note:** \`css.prefix\` and \`context\` only apply to color groups. They are ignored for general groups.
- **Theme** — \`{ id, name, tokens: Override[], spacing: Override[], general: Override[] }\`. \`tokens\` overrides color tokens; \`spacing\` and \`general\` override their respective collections. Overrides apply under a \`[data-theme="<name>"]\` selector.
- **Override** — \`{ tokenId, value? | $ref? }\`. Same value/ref rule as tokens.

### \`$ref\` format

References use a JSON-pointer-like path: \`#/color/palettes/<paletteId>/colors/<colorIndex>\`.

- \`<paletteId>\` is the palette's \`id\` field (not array index).
- \`<colorIndex>\` is a 0-based index into that palette's \`colors\` array.

Example: \`#/color/palettes/1/colors/5\` resolves to the 6th color in the palette with id 1.

### Context groups

A group with \`context: true\` generates an additional class block in \`visual-source.css\` that aliases the group's prefixed tokens to *unprefixed* CSS variables. This lets components write \`var(--text-01)\`, \`var(--border)\`, etc. and have the values resolve based on which context wrapper they're inside, via CSS custom property inheritance.

- The class name is the group's \`css.prefix\` with the trailing \`-\` stripped (e.g. prefix \`bg-\` → class \`.bg\`).
- For each token in the group whose full CSS variable name starts with the prefix, the block emits \`--<unprefixed>: var(--<full>);\` and a matching \`-rgb\` variant. Tokens whose full name does not start with the prefix (e.g. those with a \`css.name\` override that bypasses the prefix) are skipped.
- The **first** group with \`context: true\` (in array order) also applies to \`:root\`, so its tokens are the page-wide defaults.
- A context group with no \`css.prefix\` is skipped — the prefix is required for the strip-and-alias to be meaningful.

Example: a Background group with prefix \`bg-\` and tokens \`Text 01\`, \`Border\`, \`Hover\` produces:

\`\`\`css
:root, .bg {
  --text-01: var(--bg-text-01);
  --text-01-rgb: var(--bg-text-01-rgb);
  --border:  var(--bg-border);
  --border-rgb: var(--bg-border-rgb);
  --hover:   var(--bg-hover);
  --hover-rgb: var(--bg-hover-rgb);
}
\`\`\`

Consumers then write context-agnostic CSS — \`color: var(--text-01)\` — and wrap subtrees with \`<div class="error">…</div>\` to switch which context's tokens are inherited.

### General tokens

\`general.tokens\` holds arbitrary CSS values that don't belong to color or spacing — radii, fixed sizes (e.g. \`header-height\`), transition variables, z-indices, anything else.

- Each token's \`value\` is a raw CSS string (\`4px\`, \`150ms ease-in-out\`, \`64px\`, etc.).
- Each token is emitted as a single \`--<name>\` custom property in a \`/* GENERAL TOKENS */\` block. No \`-rgb\` sibling is emitted (general tokens aren't colors).
- \`general.groups\` are for **organisation/documentation only**. Unlike color groups, general groups do **not** apply a CSS prefix and do **not** generate context classes — \`css.prefix\` and \`context\` on a general group are ignored. Consumers can still set them in the manifest, but the generator skips them.
- Theme overrides for general tokens go in \`Theme.general\` and are emitted inside the same \`[data-theme="<name>"]\` block as color and spacing overrides.

Example general tokens block:

\`\`\`css
/* GENERAL TOKENS */
:root{
  --radius-sm: 4px;
  --header-height: 64px;
  --transition-fast: 150ms ease-in-out;
}
\`\`\`
`;
