import { hex_to_rgb } from '$lib/colors.js';
import { token_value, type Spec } from '$lib/spec.svelte.js';
import { kebabCase } from 'change-case';

export function generate_css(spec: Spec) {
	let css = `
/* This file was generated by Visual Source; DO NOT EDIT; */
:root {\n`;
	function append_token(name: string, value: string) {
		const rgb = hex_to_rgb(value);
		css += `\t--${name}: ${value};\n`;
		css += `\t--${name}-rgb: ${rgb[0]} ${rgb[1]} ${rgb[2]};\n`;
	}

	for (const t of spec.tokens || []) {
		const value = token_value(t);
		append_token(kebabCase(t.name), value);
	}
	css += '}\n\n';

	for (const p of spec.palettes || []) {
		css += `:root{\n`;
		const prefix = kebabCase(p.name);
		for (const [i, c] of p.colors.entries()) {
			const num = (i + 1).toString().padStart(2, '0');
			append_token(`${prefix}-${num}`, c);
		}
		css += '}\n\n';
	}
	return css.trim();
}
