import { hex_to_rgb } from '$lib/colors.js';
import { resolve_ref } from '$lib/reftype.js';
import { token_value, type Spec, type Token } from '$lib/spec.js';
import { kebabCase } from 'change-case';

export function token_css_name(
	t: Token,
	groups: { tokens: number[]; css?: { prefix?: string } }[]
) {
	if (t.css?.name) return t.css?.name;
	const g = groups?.find((g) => g.tokens.includes(t.id));
	return (g?.css?.prefix || '') + kebabCase(t.name);
}

export function generate_css(spec: Spec) {
	let css = `
/* This file was generated by Visual Source; DO NOT EDIT; */

/* COLOR TOKENS */
:root {\n`;
	function append_color_token(name: string, value: string) {
		const rgb = hex_to_rgb(value);
		css += `\t--${name}: ${value};\n`;
		css += `\t--${name}-rgb: ${rgb[0]} ${rgb[1]} ${rgb[2]};\n`;
	}

	for (const t of spec.color.tokens || []) {
		append_color_token(token_css_name(t, spec.color.groups), token_value(t, spec));
	}
	css += '}\n\n';

	for (const p of spec.color.palettes || []) {
		css += `/* PALETTE ${p.name} */\n:root{\n`;
		const prefix = kebabCase(p.name);
		for (const [i, c] of p.colors.entries()) {
			const num = (i + 1).toString().padStart(2, '0');
			append_color_token(`${prefix}-${num}`, c);
		}
		css += '}\n\n';
	}

	const context_groups = (spec.color.groups || []).filter((g) => g.context);
	context_groups.forEach((group, i) => {
		const prefix = group.css?.prefix ?? '';
		if (!prefix) return;
		const class_name = prefix.endsWith('-') ? prefix.slice(0, -1) : prefix;
		const selector = i === 0 ? `:root, .${class_name}` : `.${class_name}`;
		css += `/* CONTEXT: ${group.name} */\n${selector} {\n`;
		for (const token_id of group.tokens) {
			const token = spec.color.tokens.find((t) => t.id === token_id);
			if (!token) continue;
			const full_name = token_css_name(token, spec.color.groups);
			if (!full_name.startsWith(prefix)) continue;
			const local_name = full_name.slice(prefix.length);
			css += `\t--${local_name}: var(--${full_name});\n`;
			css += `\t--${local_name}-rgb: var(--${full_name}-rgb);\n`;
		}
		css += '}\n\n';
	});

	if (spec.spacing.scale?.length) {
		css += `/* SPACING */\n:root{\n`;
		for (const t of spec.spacing.scale || []) {
			css += `\t--${token_css_name(t, [])}: ${token_value(t, spec)};\n`;
		}
		css += '}\n\n';
	}

	for (const theme of spec.themes || []) {
		const selector = kebabCase(theme.name);
		css += `/* THEME: ${theme.name} */\n[data-theme="${selector}"] {\n`;

		for (const override of theme.tokens) {
			const baseToken = spec.color.tokens.find((t) => t.id === override.tokenId);
			if (!baseToken) continue;
			const name = token_css_name(baseToken, spec.color.groups);
			const value = override.value || (resolve_ref(spec, override.$ref!) as string);
			append_color_token(name, value);
		}

		for (const override of theme.spacing) {
			const baseToken = spec.spacing.scale.find((t) => t.id === override.tokenId);
			if (!baseToken) continue;
			const name = token_css_name(baseToken, []);
			const value = override.value || (resolve_ref(spec, override.$ref!) as string);
			css += `\t--${name}: ${value};\n`;
		}

		css += '}\n\n';
	}

	return css.trim();
}
