import { describe, it, expect, vi } from 'vitest';

vi.mock('$lib/environment/index.js', () => ({
	environment: 'browser',
	storage: { load_manifest: async () => null, write_outputs: async () => {} }
}));

import { generate_css } from './css';
import { generate_json } from './json';
import type { Spec } from '$lib/spec.svelte';

function build_spec(): Spec {
	return {
		version: 2,
		color: {
			palettes: [
				{
					id: 1,
					name: 'Blue',
					colors: ['#001f3f', '#0074d9', '#7fdbff']
				},
				{
					id: 2,
					name: 'Red',
					colors: ['#85144b', '#ff4136', '#ffb6b6']
				}
			],
			tokens: [
				// Reference into the Blue palette.
				{ id: 1, name: 'Background', $ref: '#/color/palettes/1/colors/0' },
				// Reference into the Red palette.
				{ id: 2, name: 'Accent', $ref: '#/color/palettes/2/colors/1' },
				// Literal value.
				{ id: 3, name: 'Border', value: '#cccccc' }
			],
			groups: [
				{
					id: 1,
					name: 'Surface',
					tokens: [1, 3],
					css: { prefix: 'sf-' }
				}
			]
		},
		spacing: {
			scale: [
				{ id: 1, name: 'Small', value: '0.5rem' },
				{ id: 2, name: 'Medium', value: '1rem' }
			]
		},
		themes: [
			{
				id: 1,
				name: 'Dark',
				tokens: [
					// Override Background with a literal.
					{ tokenId: 1, value: '#111111' },
					// Override Accent via $ref to a different palette swatch.
					{ tokenId: 2, $ref: '#/color/palettes/1/colors/2' as any }
				],
				spacing: [{ tokenId: 1, value: '0.25rem' }]
			}
		]
	};
}

describe('integration: palettes + tokens + theme overrides', () => {
	const spec = build_spec();
	const css = generate_css(spec);
	const json = JSON.parse(generate_json(spec));
	const manifest = JSON.parse(JSON.stringify(spec));

	describe('CSS output', () => {
		it('declares all base color tokens with their resolved hex and rgb', () => {
			expect(css).toContain('--sf-background: #001f3f;');
			expect(css).toContain('--sf-background-rgb: 0 31 63;');
			expect(css).toContain('--accent: #ff4136;');
			expect(css).toContain('--accent-rgb: 255 65 54;');
			expect(css).toContain('--sf-border: #cccccc;');
			expect(css).toContain('--sf-border-rgb: 204 204 204;');
		});

		it('declares each palette as its own block with kebab-cased prefix', () => {
			expect(css).toContain('/* PALETTE Blue */');
			expect(css).toContain('--blue-01: #001f3f;');
			expect(css).toContain('--blue-02: #0074d9;');
			expect(css).toContain('--blue-03: #7fdbff;');

			expect(css).toContain('/* PALETTE Red */');
			expect(css).toContain('--red-01: #85144b;');
			expect(css).toContain('--red-02: #ff4136;');
			expect(css).toContain('--red-03: #ffb6b6;');
		});

		it('emits the spacing block', () => {
			expect(css).toContain('/* SPACING */');
			expect(css).toContain('--small: 0.5rem;');
			expect(css).toContain('--medium: 1rem;');
		});

		it('emits a theme block that overrides only the changed tokens', () => {
			expect(css).toContain('/* THEME: Dark */');
			expect(css).toContain('[data-theme="dark"]');

			// Background token: literal override
			expect(css).toMatch(/\[data-theme="dark"\] \{[\s\S]*--sf-background: #111111;/);
			expect(css).toMatch(/\[data-theme="dark"\] \{[\s\S]*--sf-background-rgb: 17 17 17;/);

			// Accent token: $ref override resolves to Blue palette shade 3.
			expect(css).toMatch(/\[data-theme="dark"\] \{[\s\S]*--accent: #7fdbff;/);

			// Spacing override.
			expect(css).toMatch(/\[data-theme="dark"\] \{[\s\S]*--small: 0.25rem;/);

			// Border was not overridden -- it must NOT appear inside the theme block.
			const themeBlock = css.match(/\[data-theme="dark"\] \{([\s\S]*?)\}/)?.[1] ?? '';
			expect(themeBlock).not.toContain('--sf-border');
			expect(themeBlock).not.toContain('--medium');
		});

		it('begins with the do-not-edit banner', () => {
			expect(css.split('\n')[0]).toContain('generated by Visual Source');
		});
	});

	describe('manifest output', () => {
		it('preserves palettes verbatim', () => {
			expect(manifest.color.palettes).toEqual(spec.color.palettes);
		});

		it('preserves tokens including $ref strings', () => {
			expect(manifest.color.tokens[0]).toEqual({
				id: 1,
				name: 'Background',
				$ref: '#/color/palettes/1/colors/0'
			});
			expect(manifest.color.tokens[2]).toEqual({ id: 3, name: 'Border', value: '#cccccc' });
		});

		it('preserves theme overrides with both value and $ref forms', () => {
			expect(manifest.themes[0].tokens).toContainEqual({ tokenId: 1, value: '#111111' });
			expect(manifest.themes[0].tokens).toContainEqual({
				tokenId: 2,
				$ref: '#/color/palettes/1/colors/2'
			});
			expect(manifest.themes[0].spacing).toEqual([{ tokenId: 1, value: '0.25rem' }]);
		});

		it('preserves token groups with css prefix', () => {
			expect(manifest.color.groups).toEqual([
				{ id: 1, name: 'Surface', tokens: [1, 3], css: { prefix: 'sf-' } }
			]);
		});
	});

	describe('JSON output', () => {
		it('resolves base color token values', () => {
			const tokensByName = Object.fromEntries(
				json.color.tokens.map((t: any) => [t.name, t.value])
			);
			expect(tokensByName.Background).toBe('#001f3f');
			expect(tokensByName.Accent).toBe('#ff4136');
			expect(tokensByName.Border).toBe('#cccccc');
		});

		it('resolves spacing scale values', () => {
			const spacingByName = Object.fromEntries(
				json.spacing.scale.map((t: any) => [t.name, t.value])
			);
			expect(spacingByName.Small).toBe('0.5rem');
			expect(spacingByName.Medium).toBe('1rem');
		});

		it('emits a themes map keyed by theme name with overridden values', () => {
			expect(Object.keys(json.themes)).toEqual(['Dark']);
			const darkTokens = Object.fromEntries(
				json.themes.Dark.color.tokens.map((t: any) => [t.name, t.value])
			);
			expect(darkTokens.Background).toBe('#111111');
			expect(darkTokens.Accent).toBe('#7fdbff'); // $ref resolved
			expect(darkTokens.Border).toBe('#cccccc'); // unchanged

			const darkSpacing = Object.fromEntries(
				json.themes.Dark.spacing.scale.map((t: any) => [t.name, t.value])
			);
			expect(darkSpacing.Small).toBe('0.25rem');
			expect(darkSpacing.Medium).toBe('1rem');
		});

		it('resolves token groups with their token list', () => {
			const surface = json.color.groups.find((g: any) => g.name === 'Surface');
			expect(surface).toBeTruthy();
			expect(surface.tokens.map((t: any) => t.name)).toEqual(['Background', 'Border']);
			expect(surface.tokens.map((t: any) => t.value)).toEqual(['#001f3f', '#cccccc']);
		});
	});
});
